add more test for https://github.com/vmactions/freebsd-vm/issues/136

diff --git a/.github/tpl/test.tpl.yml b/.github/tpl/test.tpl.yml
--- a/.github/tpl/test.tpl.yml
+++ b/.github/tpl/test.tpl.yml
@@ -496,6 +496,38 @@ jobs:
         echo "The step was expected to fail, but it succeeded!"
         exit 1
 
+  testpass:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default success {{VM_NAME}}
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in {{VM_NAME}}
+      id: testpass
+      continue-on-error: true 
+      uses: {{GITHUB_REPOSITORY}}@{{GITHUB_SHA}}
+      with:
+        envs: 'MYTOKEN MYTOKEN2'
+        prepare: |
+          {{VM_PREPARE}}
+        mem: 4096
+        usesh: true
+        debug: true
+        run: |
+          echo "this is a normal command"
+          exit 0
+    - name: Verify that the previous step succeeded
+      if: steps.testpass.outcome != 'success'
+      run: |
+        echo "The step was expected to succeed, but it failed!"
+        exit 1
+
 
 
 
