update readme, test templates

diff --git a/.github/tpl/test.tpl.yml b/.github/tpl/test.tpl.yml
--- a/.github/tpl/test.tpl.yml
+++ b/.github/tpl/test.tpl.yml
@@ -83,6 +83,65 @@ jobs:
         pwd
 {{VM_RUN}}
 
+  testnfs:
+    if: ${{ !contains(github.repository, 'netbsd') && !contains(github.repository, 'openbsd') && !contains(github.repository, 'dragonflybsd') && !contains(github.repository, 'omnios')}}
+    strategy:
+      matrix:
+        release: [ {{TEST_RELEASES}}, ""]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest"]
+    runs-on: ${{ matrix.runs }}
+    name: nfs {{VM_NAME}}
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      DEBUG: 1
+    steps:
+    - uses: actions/checkout@v4
+    - name: Creating Web console
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
+    - name: Test in {{VM_NAME}}
+      id: test
+      uses: {{GITHUB_REPOSITORY}}@{{GITHUB_SHA}}
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          {{VM_PREPARE}}
+        release: ${{ matrix.release }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: nfs
+        run: |
+          ls -lah /root/work
+          tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+{{VM_RUN}}
+
+    - name: Test NAT
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      shell: {{VM_OS_NAME}} {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+{{VM_RUN}}
+
 
   test:
     strategy:
