fix https://github.com/vmactions/freebsd-vm/issues/136

diff --git a/.github/tpl/test.tpl.yml b/.github/tpl/test.tpl.yml
--- a/.github/tpl/test.tpl.yml
+++ b/.github/tpl/test.tpl.yml
@@ -464,6 +464,43 @@ jobs:
 
 
 
+  testerr:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default {{VM_NAME}}
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in {{VM_NAME}}
+      id: testerr
+      continue-on-error: true 
+      uses: {{GITHUB_REPOSITORY}}@{{GITHUB_SHA}}
+      with:
+        envs: 'MYTOKEN MYTOKEN2'
+        prepare: |
+          {{VM_PREPARE}}
+        mem: 4096
+        usesh: true
+        debug: true
+        run: |
+          echo "this is an error"
+          exit 1
+    - name: Verify that the previous step failed
+      if: steps.testerr.outcome != 'failure'
+      run: |
+        echo "The step was expected to fail, but it succeeded!"
+        exit 1
+
+
+
+
+
+
 
 
 
